spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:./.local/h2/devdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  auth:
    jwt:
      secret: coolscretcoolscretcoolscretcoolscretcoolscret
      access-valid: 1d
      refresh-valid: 1d
google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
server:
  error:
    include-stacktrace: never
logging:
  level:
    org:
      hibernate:
        sql: debug